### ISSUE TITLE
NES adapter recognized in Win10 but not responding

### ISSUE THREAD

**Issue by quaelgeist** [MickGyver/DaemonBite-Retro-Controllers-USB#10]
Hi guys.

I have wired up the NES adapter and it shows up as two gamepads in win10.
But a confirmed as working NES pad produces no response from any of those two.

Has anybody ever had this problem before?

regards,
Michael

**Comment by MickGyver** [comment]
Probably something wrong with the wiring. Did you connect all wires of the connector, including 5V and GND?

**Comment by quaelgeist** [comment]
thanks for the answer

Yes, all are connected. latch, clock, gnd, data1 and vcc (thats the 5V, right?)
also created the solder bridge and checked the wires of the extension plug with a multimeter to make sure i wasn't mixing them up. Solder points look and feel solid.

**Comment by quaelgeist** [comment]
Well, reproduce me sideways, but after trying yet again, it suddenly works perfectly. I guess it was Windows and not the Arduino that was pulling my leg here all the time :-|

**Comment by MickGyver** [comment]
Good to hear it's working! :)
