### ISSUE TITLE
SNES - Latest version of .ino detects 8bitdo SN30 (2.4ghz) as NES controller

### ISSUE THREAD

**Issue by italiangrandma** [MickGyver/DaemonBite-Retro-Controllers-USB#6]
Title. When plugged into MiSTer, the adapter was detecting my wireless SN30 as a NES controller instead of a SNES controller (A, X, L and R did not respond when trying to map). I reverted to the previous version and all is now well.

**Comment by MickGyver** [comment]
Someone else made a pull request to fix NES detection, I accepted it without reviewing it properly. I reverted that pull request now.
