### ISSUE TITLE
Feature Request: PC game port (D-Sub 15) support

### ISSUE THREAD

**Issue by rmueller83** [MickGyver/DaemonBite-Retro-Controllers-USB#8]
I have some old Gravis Gamepads & Analog Pro Joysticks, which would be nice to use with MiSTer ao486 or the new MS FlightSim. I found another project which uses the larger Arduino Leonardo which perhaps could be used as a template: https://github.com/shadwork/Arduino-PC-Gameport-HID

**Comment by MickGyver** [comment]
Thanks for the heads up! I am working on a PC gameport adapter. I have basic 2-4 analog axis and four button controllers working. The Gravis Gamepad also works. I'm currently working with the Microsoft Sidewinder range.

**Comment by rmueller83** [comment]
@MickGyver has the PC gameport support been removed?
