### ISSUE TITLE
How do you wire SNES up for 2 pads support?

### ISSUE THREAD

**Issue by shanotype** [MickGyver/DaemonBite-Retro-Controllers-USB#9]
I done this mod for USB SNES but how do you go about adding another Snes pad to it? Saves me using another board.

**Comment by MickGyver** [comment]
All the wires of both the connector are shared except for the data line. Data of port 1 should be connected to DATA1, data of port 2 should be connected to DATA2.

**Comment by shanotype** [comment]
Thank you! Makes sense. :)
